name: Testes Automatizados
# deixei como pull request para testar
on: [push] 

jobs:
  testes-automatizados:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start