name: Testes Automatizados
# deixei como pull request para testar
on: pull_request 

jobs:
  testes-automatizados:
    runs-on: windows-latest

    steps:
    - uses: action/checkout@v3
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - name: run install, build and test
      run: |
        npm install
        npm run build
        npm install cypress --save-dev
        npx cypress open